name: Build and Push Docker Images

# This is the trigger: Run this job on any push to the 'main' branch
on:
  push:
    branches: [ "main" ]

jobs:
  build-services:
    runs-on: ubuntu-latest # Use a standard Linux runner
    
    # This is the 0.01% trick: a "matrix"
    # This runs the *same* job twice, in parallel,
    # once for each 'service' in the list.
    strategy:
      matrix:
        service: [ 'bidder-service', 'impression-simulator' ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          # This is your GitHub username. Username should be in lowercase
          username: kishanraj0007
          # This is a temporary password. GitHub Actions creates
          # it for us automatically. It's very secure.
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          # Tell Docker the path to the Dockerfile
          context: ${{ matrix.service }}
          push: true
          # This creates the image name, e.g.,
          # ghcr.io/your-username/bidder-service:latest --> username shoud be in lowercase
          tags: ghcr.io/kishanraj0007/${{ matrix.service }}:latest