name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]

jobs:
  build-services:
    runs-on: ubuntu-latest # Use a standard Linux runner
    
    permissions:
      contents: read  # Needed to check out code
      packages: write # Needed to push Docker images
      
    strategy:
      matrix:
        service: [ 'bidder-service', 'impression-simulator' ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: kishanraj0007
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          # Tell Docker the path to the Dockerfile
          context: ${{ matrix.service }}
          push: true
          tags: ghcr.io/kishanraj0007/${{ matrix.service }}:latest